### ISSUE TITLE
dRRt unclear

### ISSUE THREAD

**Issue by guanyafu** [delton137/PIMD-F90#1]
In MD.f90, momentum is updated through PPt = PPt - MASSCON*dRRt*delt2 (line49), which means that dRRt is the derivative of potential. However, the 166th line of force_calc.f90 reads dRR=-1d0*dRR*EVTOKCALPERMOLE, which means that dRRt is force. It is quite confusing.

**Comment by delton137** [comment]
Yes, 

The reason for that is that this code originally created as an MD code for use with the TTM3F potential code. The TTM3F potential code returns an array dRR, which is the derivative of the potential in kcal/mol. The rest of the code is based off that. When forces are needed in the MD integration, it is multiplied by -1 and also converted into more standard units (based on Angstroms, ps, amu, I believe).

However, in line 166 of force_calc.f90, we are getting forces from SIESTA (a DFT code), which returns forces, not the derivatives. TO make it consistent with the rest of the code we have to multiply by -1 to convert it. It also has to be converted to kcal/mol

I know it is confusing.
