### ISSUE TITLE
recalculate the coordinates of centroids

### ISSUE THREAD

**Issue by guanyafu** [delton137/PIMD-F90#2]
After calling subroutine initialize_beads, the position of centroids is different from the original ones. Should the coordinates of centroids be recalculated?

**Comment by delton137** [comment]
Hi, technically yes they should be. The issue would be corrected during the first pass through the MD integration, so it's not a fatal error, but it is a mistake. Thanks for the fix. 

I fixed it by adding the following line: 

`RRc = sum(RRt,3)/Nbeads !adjust RRc after bead generation`

to compute the centroid toward the end of initialize_beads

changes have been pushed to the repo
